# Generated by Django 5.2 on 2026-07-20 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Workplace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "table_number",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Номер стола"
                    ),
                ),
                (
                    "extra_info",
                    models.TextField(
                        blank=True, verbose_name="Дополнительная информация"
                    ),
                ),
            ],
            options={
                "verbose_name": "Рабочее место",
                "verbose_name_plural": "Рабочие места",
            },
        ),
    ]
